site_name: Atlansec
site_url: https://atlansec.es
theme:
  favicon: assets/favicon.png
  name: material
  features:
    - hide_title
    - navigation.indexes
    - navigation.tabs
    - content.code.copy
  palette:
    primary: white
  icon:
  logo: assets/logo.png
  custom_dir: "docs/overrides"

extra_css:
  - stylesheets/extra.css

nav:
  - Home:
      - index.md
  - Services:
      - services/index.md
  - Blog:
      - blog/index.md
  

plugins:
  - search
  - social
  - blog:
      categories: false
      categories_name: Categories


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
