site_name: Atlansec
site_url: https://atlansec.es
theme:
  search_index_only: false  
  favicon: ../assets/images/favicon.png
  logo: ../assets/images/logo.png
  custom_dir: "docs/overrides"
  name: material
  features:
    - hide_title
    - navigation.indexes
    - navigation.tabs
    - content.code.copy
    - i18n
    - search.share
  palette:
    primary: white

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - Services: services/index.md
  - Blog: blog/index.md

plugins:
  - search
  - tags
  - social
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Spanish
          build: true
          nav_translations:
            Home: Inicio
            Services: Servicios
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - meta